### PR TITLE
Fix user creation time being zero.

### LINKED ISSUE #195: Wrong creation date for new accounts
## Describe the bug
Newly created accounts report `"0001-01-01T00:00:00Z"` in `createdAt` field.

## To Reproduce
1. Go to skynetfree.net
2. Create an account
3. Open devtools and inspect `/user` response.

## Expected behavior
Default to current datetime, I think?

## Screenshots
image

### PR DESCRIPTION
**Pull request by ro-tex**
# PULL REQUEST

## Checklist
Review and complete the checklist to ensure that the PR is complete before assigned to an approver.
 - [ ] All new methods or updated methods have clear docstrings
 - [ ] Testing added or updated for new methods
 - [ ] Verify if any changes impact the WebPortal Health Checks
 - [ ] Approriate documentation updated
 - [ ] Changelog file created

## Issues Closed
Closes #195

### CODE REVIEW

File: test/api/handlers_test.go [hunk 1]
```diff
@@ -133,6 +133,11 @@ func testHandlerUserPOST(t *testing.T, at *test.AccountsTester) {
 	if err != nil {
 		t.Fatal("Error while fetching the user from the DB. Error ", err.Error())
 	}
+	// Make sure the creation timestamp is correct.
+	now := time.Now().UTC()
+	if u.CreatedAt.Before(now.Add(-1*time.Minute)) || u.CreatedAt.After(now.Add(time.Minute)) {
```
Comment (MSevey) [inline test/api/handlers_test.go:138]: nit: would it not be sufficient to just verify that the timestamp is not zero?

**Review by MSevey — APPROVED** [review]

File: test/api/handlers_test.go (hunk 1 above)
Comment (ro-tex) [reply test/api/handlers_test.go:138]: For this particular issue - yes, I can just compare to the zero value. But since we're adding a check anyway, we might as well make sure the time is accurate. This would catch, for example, an omitted `.UTC()` call and other things like that.

File: database/user.go [hunk 2]
```diff
@@ -334,8 +330,18 @@ func (db *DB) UserCreate(ctx context.Context, emailAddr, pass, sub string, tier
...
 		Tier:                             tier,
+		CreatedAt:                        time.Now().UTC(),
+		MigratedAt:                       time.Time{},
+		SubscribedUntil:                  time.Time{},
+		SubscriptionStatus:               "",
+		SubscriptionCancelAt:             time.Time{},
+		SubscriptionCancelAtPeriodEnd:    false,
+		StripeID:                         "",
+		QuotaExceeded:                    false,
+		PubKeys:                          make([]PubKey, 0),
```
Comment (peterjan) [inline database/user.go:344]: this removes the need for that type query right?

File: database/user.go [hunk 3]
```diff
@@ -334,8 +330,18 @@ func (db *DB) UserCreate(ctx context.Context, emailAddr, pass, sub string, tier
 		EmailConfirmationToken:           emailConfToken,
 		EmailConfirmationTokenExpiration: time.Now().UTC().Add(EmailConfirmationTokenTTL).Truncate(time.Millisecond),
 		PasswordHash:                     string(passHash),
+		RecoveryToken:                    "",
 		Sub:                              sub,
 		Tier:                             tier,
+		CreatedAt:                        time.Now().UTC(),
+		MigratedAt:                       time.Time{},
```
Comment (peterjan) [inline database/user.go:337]: what's the reason we explicitly define these defaults?

File: test/api/handlers_test.go (hunk 1 above)
Comment (peterjan) [reply test/api/handlers_test.go:138]: `nit` could use `Truncate` maybe 

```go
if u.CreatedAt.Truncate(time.Minute) != now.Truncate(time.Minute)
```

**Review by peterjan — APPROVED** [review]

File: test/api/handlers_test.go (hunk 1 above)
Comment (ro-tex) [reply test/api/handlers_test.go:138]: > `nit` could use `Truncate` maybe
> 
> ```go
> if u.CreatedAt.Truncate(time.Minute) != now.Truncate(time.Minute)
> ```

That opens us up to NDFs. `Truncate` doesn't round, it just drops the rest of the time, so 12:10:59.99 will truncate to 12:10 and 12:11:00.01 will truncate to 12:11.

File: database/user.go (hunk 2 above)
Comment (ro-tex) [reply database/user.go:344]: We still have all pre-existing users who don't have any pubkeys.
